# Generated by Django 3.1.5 on 2021-02-03 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nicname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('userID', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('name', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='api.user')),
            ],
        ),
    ]
