# Generated by Django 3.1.5 on 2021-02-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('post', models.ForeignKey(db_column='post', on_delete=django.db.models.deletion.CASCADE, related_name='post', to='api.post')),
            ],
        ),
    ]
